language: csharp
solution: TP_WF_lab5.sln 
install:
- nuget restore ./TP_WF_lab5/TP_WF_lab5.sln
- nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
- xbuild /p:Configuration=Release TP_WF_lab5/TP_WF_lab5.sln
- mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./TP_WF_lab5/Tests/bin/Release/Tests.dll
